[theme]
primaryColor             = "#F06A00"
backgroundColor          = "#f4f5f7"
secondaryBackgroundColor = "#ffffff"
textColor                = "#172b4d"
font                     = "sans serif"

[server]
headless            = true
enableCORS          = false
enableXsrfProtection = true
maxUploadSize       = 50

[browser]
gatherUsageStats    = false

[logger]
level               = "warning"
